// app/(private)/settings/_components/section-accounts/provider-account-item/provider-account-item.tsx
import { Badge, Group, Text } from '@mantine/core'
import type { Icon } from '@tabler/icons-react'
import { ProviderLinkButton } from '../provider-link-button/provider-link-button'
import { ProviderUnlinkButton } from '../provider-unlink-button/provider-unlink-button'

type ProviderAccountItemProps = {
  label: string
  icon: Icon
  linked: boolean
  busy: boolean
  onLink: () => void
  onUnlink?: () => void
}

export function ProviderAccountItem({
  label,
  icon: Icon,
  linked,
  busy,
  onLink,
  onUnlink,
}: ProviderAccountItemProps) {
  const badge = linked ? (
    <Badge size="sm" variant="light" color="green">
      Vinculada
    </Badge>
  ) : (
    <Badge size="sm" variant="outline" color="gray">
      Não vinculada
    </Badge>
  )

  const action = linked ? (
    <ProviderUnlinkButton busy={busy} onClick={() => onUnlink?.()} />
  ) : (
    <ProviderLinkButton onClick={onLink} />
  )

  return (
    <div className="flex items-center justify-between gap-2">
      <Group gap="sm">
        <Icon size={18} />
        <Text>{label}</Text>
        {badge}
      </Group>
      {action}
    </div>
  )
}

// apps/sveltekit/src/lib/components/ProviderAccountItem.svelte
<script lang="ts">
  import { IconExternalLink, IconLinkOff, type Icon as IconType } from '@tabler/icons-svelte'

  interface Props {
    label: string
    icon: IconType
    linked: boolean
    busy: boolean
    onlink: () => void
    onunlink: () => void
  }

  let { label, icon: Icon, linked, busy, onlink, onunlink }: Props = $props()
</script>

<div class="flex flex-wrap items-center justify-between gap-2">
  <div class="flex min-w-0 items-center gap-3">
    <Icon class="size-[18px] shrink-0" />
    <span>{label}</span>
    {#if linked}
      <span class="badge preset-tonal-success">Vinculada</span>
    {:else}
      <span class="badge preset-tonal">Não vinculada</span>
    {/if}
  </div>

  {#if linked}
    <button
      type="button"
      class="btn btn-xs preset-tonal-error"
      disabled={busy}
      onclick={() => onunlink()}
    >
      <IconLinkOff class="size-4" />
      Desvincular
    </button>
  {:else}
    <button type="button" class="btn btn-xs preset-tonal" disabled={busy} onclick={() => onlink()}>
      <IconExternalLink class="size-4" />
      Vincular
    </button>
  {/if}
</div>
