// apps/nuxt/app/pages/busca/_components/form-nl-search.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useNotifications } from '~/lib/utils/notifications'
import { useNlSearchMutation } from '~/services/assistant/assistant.mutation'
import CardSearchResultList from './card-search-result-list/card-search-result-list.vue'

const { notifyError } = useNotifications()
const { mutate, isPending, data: result } = useNlSearchMutation()

const query = ref('')

function handleSearch() {
  if (!query.value.trim()) return
  mutate(query.value, { onError: notifyError('Não consegui buscar') })
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter') handleSearch()
}
</script>

<template>
  <div class="flex max-w-4xl flex-col gap-4">
    <div>
      <h1 class="text-highlighted text-3xl/tight font-bold">Busca em linguagem natural</h1>
      <p class="text-dimmed text-sm">
        Descreva o que procura em texto livre — a IA converte em filtros e aplica sobre suas
        tarefas.
      </p>
    </div>

    <div class="flex items-center gap-3">
      <UInput
        v-model="query"
        class="flex-1"
        placeholder="Ex.: consultas de amanhã de alta prioridade"
        @keydown.enter="handleKeydown"
      >
        <template #trailing>
          <UKbd>↵</UKbd>
        </template>
      </UInput>

      <UButton
        icon="i-tabler:search"
        :loading="isPending"
        :disabled="!query.trim()"
        @click="handleSearch"
      >
        Buscar
      </UButton>
    </div>

    <CardSearchResultList :result="result" :is-pending="isPending" />
  </div>
</template>

// app/busca/_components/form-nl-search.tsx
'use client'

import { useState, type KeyboardEvent } from 'react'
import { Button, Group, Kbd, Text, TextInput, Title } from '@mantine/core'
import { IconSearch } from '@tabler/icons-react'
import { useNlSearchMutation } from '@/services/assistant/assistant.mutation'
import { notifyError } from '@/lib/utils/notifications'
import { CardSearchResultList } from './card-search-result-list/card-search-result-list'

export function FormNlSearch() {
  const { data: result, isPending, mutate } = useNlSearchMutation()
  const [query, setQuery] = useState<string>('')

  const handleSearch = () => mutate(query, { onError: notifyError('Não consegui buscar') })

  const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter' && query.trim()) handleSearch()
  }

  return (
    <div className="flex max-w-4xl flex-col gap-4">
      <div>
        <Title order={3}>Busca em linguagem natural</Title>
        <Text size="sm" c="dimmed">
          Descreva o que procura em texto livre — a IA converte em filtros e aplica sobre suas
          tarefas.
        </Text>
      </div>

      <Group>
        <TextInput
          placeholder="Ex.: consultas de amanhã de alta prioridade"
          value={query}
          onChange={(event) => setQuery(event.currentTarget.value)}
          onKeyDown={handleKeyDown}
          className="flex-1"
          rightSection={<Kbd>↵</Kbd>}
        />
        <Button
          leftSection={<IconSearch size={18} />}
          loading={isPending}
          disabled={!query.trim()}
          onClick={handleSearch}
        >
          Buscar
        </Button>
      </Group>

      <CardSearchResultList result={result} isPending={isPending} />
    </div>
  )
}
