// app/(public)/login/page.tsx
import { Suspense } from 'react'
import type { Metadata } from 'next'
import { CardAuth } from '../_components/card-auth/card-auth'
import { FormLogin } from './_components/form-login/form-login'

export const metadata: Metadata = {
  title: 'Entrar | ia-task-manager',
}

type LoginPageProps = {
  searchParams: Promise<{ next?: string }>
}

export default async function LoginPage({ searchParams }: LoginPageProps) {
  const { next } = await searchParams

  return (
    <CardAuth title="ia-task-manager">
      <Suspense>
        <FormLogin callbackURL={next} />
      </Suspense>
    </CardAuth>
  )
}

// apps/sveltekit/src/routes/(public)/login/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import CardAuth from '../_components/card-auth/card-auth.svelte'
  import FormLogin from './_components/form-login/form-login.svelte'
  import { paths, type TPath } from '$lib/constants/paths'

  const callbackURL = (page.url.searchParams.get('next') || paths.DASHBOARD) as TPath
</script>

<svelte:head>
  <title>Entrar | ia-task-manager</title>
</svelte:head>

<CardAuth title="ia-task-manager">
  <FormLogin {callbackURL} />
</CardAuth>
