// apps/nuxt/app/components/ThemeSwitcher.vue
<script setup lang="ts">
import type { DropdownMenuItem } from '@nuxt/ui'
import { computed } from 'vue'
import { useColorMode } from '#imports'

const colorMode = useColorMode()

const options = [
  { value: 'auto', label: 'Sistema', icon: 'i-tabler:device-desktop' },
  { value: 'light', label: 'Claro', icon: 'i-tabler:sun' },
  { value: 'dark', label: 'Escuro', icon: 'i-tabler:moon' },
] as const

const items = computed<DropdownMenuItem[]>(() => [
  { label: 'Tema', type: 'label' },
  ...options.map((option) => ({
    label: option.label,
    icon: option.icon,
    type: 'checkbox' as const,
    checked: colorMode.preference === option.value,
    onSelect: (event: Event) => event.preventDefault(),
    onUpdateChecked: () => {
      colorMode.preference = option.value
    },
  })),
])
</script>

<template>
  <UDropdownMenu :items="items" :content="{ align: 'end', collisionPadding: 12 }">
    <UButton
      color="neutral"
      variant="ghost"
      aria-label="Alternar tema"
      title="Alternar tema"
      square
    >
      <span aria-hidden="true" class="dark:hidden"
        ><UIcon name="i-tabler:sun" class="size-5"
      /></span>
      <span aria-hidden="true" class="hidden dark:inline"
        ><UIcon name="i-tabler:moon" class="size-5"
      /></span>
    </UButton>
  </UDropdownMenu>
</template>

// apps/nextjs/components/theme-switcher/theme-switcher.tsx
'use client'

import { Button, Menu, useMantineColorScheme } from '@mantine/core'
import { IconCheck, IconDeviceDesktop, IconMoon, IconSun } from '@tabler/icons-react'

const THEME_OPTIONS = [
  { value: 'auto', label: 'Sistema', icon: IconDeviceDesktop },
  { value: 'light', label: 'Claro', icon: IconSun },
  { value: 'dark', label: 'Escuro', icon: IconMoon },
] as const

export function ThemeSwitcher() {
  const { colorScheme, setColorScheme } = useMantineColorScheme()

  return (
    <Menu position="bottom-end" width={150}>
      <Menu.Target>
        <Button variant="subtle" px={6} aria-label="Alternar tema" title="Alternar tema">
          <span aria-hidden="true" className="dark:hidden">
            <IconSun size={18} />
          </span>
          <span aria-hidden="true" className="hidden dark:inline">
            <IconMoon size={18} />
          </span>
        </Button>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Label>Tema</Menu.Label>
        {THEME_OPTIONS.map((option) => {
          const Icon = option.icon

          return (
            <Menu.Item
              key={option.value}
              leftSection={<Icon size={16} />}
              rightSection={colorScheme === option.value ? <IconCheck size={14} /> : null}
              onClick={() => setColorScheme(option.value)}
            >
              {option.label}
            </Menu.Item>
          )
        })}
      </Menu.Dropdown>
    </Menu>
  )
}
