// apps/nuxt/app/components/render-boundary/render-boundary.vue
<script setup lang="ts">
defineProps<{
  status: 'pending' | 'error' | 'ready'
  errorMessage?: string
  retryLabel?: string
  retry?: boolean
}>()

const emit = defineEmits<{ retry: [] }>()
</script>

<template>
  <ErrorState
    v-if="status === 'error' && !$slots.errorSnippet"
    :message="errorMessage"
    :retry="retry"
    :retry-label="retryLabel"
    @retry="emit('retry')"
  />

  <slot v-else-if="status === 'error'" name="errorSnippet" />
  <slot v-else-if="status === 'pending'" name="fallback">
    <SkeletonStack />
  </slot>
  <slot v-else />
</template>

// apps/sveltekit/src/lib/components/render-boundary/render-boundary.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import ErrorState from '../error-state/error-state.svelte'
  import SkeletonStack from '../skeleton-stack/skeleton-stack.svelte'

  let {
    status,
    errorMessage,
    retryLabel,
    onretry,
    children,
    fallback,
    errorSnippet,
  }: {
    status: 'pending' | 'error' | 'ready'
    errorMessage?: string
    retryLabel?: string
    onretry?: () => void
    children: Snippet
    fallback?: Snippet
    errorSnippet?: Snippet
  } = $props()
</script>

{#if status === 'error'}
  {#if errorSnippet}
    {@render errorSnippet()}
  {:else}
    <ErrorState message={errorMessage} retry={!!onretry} {retryLabel} {onretry} />
  {/if}
{:else if status === 'pending'}
  {#if fallback}
    {@render fallback()}
  {:else}
    <SkeletonStack />
  {/if}
{:else}
  {@render children()}
{/if}
