// app/resumo/_components/card-day-summary.tsx
'use client'

import { Button, Group, Text } from '@mantine/core'
import { IconSparkles } from '@tabler/icons-react'
import { notifyError } from '@/lib/utils/notifications'
import { useSummarizeDayMutation } from '@/services/insights/insights.mutation'
import { EmptyState } from './empty-state/empty-state'
import { CardDaySummaryContent } from './card-day-summary-content/card-day-summary-content'

export function CardDaySummary() {
  const { data: summary, isPending, isError, mutate } = useSummarizeDayMutation()

  return (
    <div className="flex flex-col gap-4">
      <Group justify="flex-end">
        <Button
          leftSection={<IconSparkles size={18} />}
          loading={isPending}
          onClick={() => mutate(undefined, { onError: notifyError('Não consegui gerar o resumo') })}
        >
          Gerar resumo
        </Button>
      </Group>

      {isError && (
        <Text size="sm" c="red">
          Não foi possível gerar o resumo agora. Verifique a configuração da IA e tente novamente.
        </Text>
      )}

      <CardDaySummaryContent summary={summary} isPending={isPending} />
      {!summary && !isPending && (
        <EmptyState message="Gere um resumo para ver o plano de execução do dia." />
      )}
    </div>
  )
}

// apps/sveltekit/src/routes/(private)/resumo/_components/card-day-summary.svelte
<script lang="ts">
  import { IconSparkles } from '@tabler/icons-svelte'
  import CardDaySummaryContent from './card-day-summary-content/card-day-summary-content.svelte'
  import EmptyState from '$lib/components/empty-state/empty-state.svelte'
  import { useSummarizeDayMutation } from '$lib/services/insights/insights.mutation'
  import { notifyError } from '$lib/utils/notifications'

  const summaryMutation = useSummarizeDayMutation()

  const summary = $derived(summaryMutation.data)
  const isPending = $derived(summaryMutation.isPending)
  const error = $derived(summaryMutation.error)

  function handleGenerate(): void {
    summaryMutation.mutate(undefined, {
      onError: (failure) => notifyError('Não consegui gerar o resumo')(failure),
    })
  }
</script>

<div class="flex flex-col gap-4">
  <div class="flex justify-end">
    <button
      type="button"
      class="btn preset-filled-primary-500"
      aria-busy={isPending}
      disabled={isPending}
      onclick={handleGenerate}
    >
      <IconSparkles class="size-[18px]" />
      {summary ? 'Gerar novo resumo' : 'Gerar resumo'}
    </button>
  </div>

  {#if error}
    <p class="text-error text-sm">
      Não foi possível gerar o resumo agora. Verifique a configuração da IA e tente novamente.
    </p>
  {/if}

  <CardDaySummaryContent {summary} {isPending} />

  {#if !summary && !isPending}
    <EmptyState message="Gere um resumo para ver o plano de execução do dia." />
  {/if}
</div>
