// apps/nuxt/app/pages/settings/_components/section-security/section-security.vue
<script setup lang="ts">
import { reactive } from 'vue'
import { changePasswordSchema } from '@ia-task-manager/schemas/auth'
import type { ChangePasswordInput } from '@ia-task-manager/schemas/auth'
import { useNotifications } from '~/lib/utils/notifications'
import { useChangePasswordMutation } from '~/services/auth/auth.mutation'

const { notifyError, notifySuccess } = useNotifications()
const changePasswordMutation = useChangePasswordMutation()

const state = reactive<ChangePasswordInput>({ currentPassword: '', newPassword: '' })

function onSubmit() {
  changePasswordMutation.mutate(
    { currentPassword: state.currentPassword, newPassword: state.newPassword },
    {
      onError: notifyError('Não foi possível alterar a senha'),
      onSuccess: () => {
        notifySuccess('Senha alterada', 'Sua senha foi atualizada com sucesso.')
        state.currentPassword = ''
        state.newPassword = ''
      },
    },
  )
}
</script>

<template>
  <UCard class="animate-in fade-in duration-base ease-entrance max-w-md">
    <div class="flex flex-col gap-4">
      <h2 class="text-highlighted font-semibold">Alterar senha</h2>

      <UForm :schema="changePasswordSchema" :state="state" :transform="false" @submit="onSubmit">
        <div class="flex flex-col gap-4">
          <UFormField label="Senha atual" name="currentPassword" required>
            <UInput
              v-model="state.currentPassword"
              class="w-full"
              type="password"
              placeholder="Sua senha atual"
            />
          </UFormField>

          <UFormField label="Nova senha" name="newPassword" required>
            <UInput
              v-model="state.newPassword"
              class="w-full"
              type="password"
              placeholder="Mínimo de 8 caracteres"
            />
          </UFormField>

          <UButton
            type="submit"
            class="self-start"
            :loading="changePasswordMutation.isPending.value"
          >
            Alterar senha
          </UButton>
        </div>
      </UForm>
    </div>
  </UCard>
</template>

// apps/sveltekit/src/routes/(private)/settings/_components/section-security/section-security.svelte
<script lang="ts">
  import { changePasswordSchema } from '@ia-task-manager/schemas/auth'
  import type { ChangePasswordInput } from '@ia-task-manager/schemas/auth'
  import { z } from 'zod'
  import { useChangePasswordMutation } from '$lib/services/auth/auth.mutation'
  import { notifyError, notifySuccess } from '$lib/utils/notifications'

  const changePasswordMutation = useChangePasswordMutation()

  let passwordState: ChangePasswordInput = $state({ currentPassword: '', newPassword: '' })
  let errors = $state<{ currentPassword?: string[]; newPassword?: string[] }>({})

  function handleSubmit(event: SubmitEvent): void {
    event.preventDefault()
    const parsed = changePasswordSchema.safeParse({
      currentPassword: passwordState.currentPassword,
      newPassword: passwordState.newPassword,
    })
    if (!parsed.success) {
      errors = z.flattenError(parsed.error).fieldErrors
      return
    }
    errors = {}
    changePasswordMutation.mutate(
      { currentPassword: parsed.data.currentPassword, newPassword: parsed.data.newPassword },
      {
        onError: notifyError('Não foi possível alterar a senha'),
        onSuccess: () => {
          notifySuccess('Senha alterada', 'Sua senha foi atualizada com sucesso.')
          passwordState.currentPassword = ''
          passwordState.newPassword = ''
        },
      },
    )
  }
</script>

<div
  class="animate-in fade-in duration-base ease-entrance card border-line bg-surface border max-w-md p-6"
>
  <div class="flex flex-col gap-4">
    <h2 class="text-fg font-semibold">Alterar senha</h2>

    <form class="flex flex-col gap-4" novalidate onsubmit={handleSubmit}>
      <div class="flex flex-col gap-1">
        <label class="label-text" for="security-current-password">Senha atual</label>
        <input
          id="security-current-password"
          name="currentPassword"
          type="password"
          class="input"
          placeholder="Sua senha atual"
          bind:value={passwordState.currentPassword}
        />
        {#if errors.currentPassword}
          <span class="text-error text-xs">{errors.currentPassword[0]}</span>
        {/if}
      </div>

      <div class="flex flex-col gap-1">
        <label class="label-text" for="security-new-password">Nova senha</label>
        <input
          id="security-new-password"
          name="newPassword"
          type="password"
          class="input"
          placeholder="Mínimo de 8 caracteres"
          bind:value={passwordState.newPassword}
        />
        {#if errors.newPassword}
          <span class="text-error text-xs">{errors.newPassword[0]}</span>
        {/if}
      </div>

      <button
        type="submit"
        class="btn preset-filled-primary-500 self-start"
        disabled={changePasswordMutation.isPending}
      >
        Alterar senha
      </button>
    </form>
  </div>
</div>
