// apps/nuxt/app/components/ModalTodoForm.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { createTodoSchema } from '@ia-task-manager/schemas/todo'
import type { CreateTodoFormInput, Todo, TodoPriority } from '@ia-task-manager/schemas/todo'
import { priorityOptions } from '~/lib/constants/todo.constants'
import { toDateInputValue } from '~/lib/utils/date'

type TodoFormState = {
  title: string
  description: string
  priority: TodoPriority
  dueDate: string
}

const props = defineProps<{ mode: 'create' | 'edit'; todo?: Todo }>()
const emit = defineEmits<{ submit: [values: CreateTodoFormInput]; close: [] }>()

const open = ref(true)

const state = reactive<TodoFormState>({
  title: props.todo?.title ?? '',
  description: props.todo?.description ?? '',
  priority: props.todo?.priority ?? 'medium',
  dueDate: props.todo?.dueDate ? toDateInputValue(props.todo.dueDate) : '',
})

function onUpdateOpen(value: boolean) {
  open.value = value
  if (!value) emit('close')
}

function onSubmit() {
  emit('submit', { ...state })
}
</script>

<template>
  <UModal
    :open="open"
    :title="props.mode === 'edit' ? 'Editar tarefa' : 'Nova tarefa'"
    @update:open="onUpdateOpen"
  >
    <UForm :schema="createTodoSchema" :state="state" :transform="false" @submit="onSubmit">
      <div class="flex flex-col gap-4">
        <UFormField label="Título" name="title" required>
          <UInput v-model="state.title" class="w-full" placeholder="Ex.: Preparar apresentação" />
        </UFormField>

        <UFormField label="Descrição" name="description">
          <UTextarea
            v-model="state.description"
            class="w-full"
            autoresize
            :rows="2"
            :maxrows="5"
            placeholder="Detalhes da tarefa (opcional)"
          />
        </UFormField>

        <UFormField label="Prioridade" name="priority">
          <USelect v-model="state.priority" class="w-full" :options="priorityOptions" />
        </UFormField>

        <UFormField label="Vencimento" name="dueDate">
          <UInput v-model="state.dueDate" class="w-full" type="date" />
        </UFormField>

        <div class="flex justify-end gap-2">
          <UButton icon="i-tabler:x" variant="subtle" @click="emit('close')">Cancelar</UButton>
          <UButton type="submit">
            {{ props.mode === 'edit' ? 'Salvar' : 'Criar tarefa' }}
          </UButton>
        </div>
      </div>
    </UForm>
  </UModal>
</template>

// apps/nextjs/app/(private)/tarefas/_components/modal-todo-form/modal-todo-form.tsx
'use client'

import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button, Group, Modal, Select, Stack, TextInput, Textarea } from '@mantine/core'
import { IconX } from '@tabler/icons-react'
import type { Todo } from '@ia-task-manager/schemas/todo'
import { priorityOptions } from '@/lib/constants/todo.constants'
import { toDateInputValue } from '@/lib/utils/date'
import { createTodoSchema, type CreateTodoFormInput } from '@ia-task-manager/schemas/todo'

export type TodoFormInput = CreateTodoFormInput

type ModalTodoFormProps = {
  mode: 'create' | 'edit'
  todo?: Todo
  onSubmit: (values: TodoFormInput) => void
  onClose: () => void
}

export function ModalTodoForm({ mode, todo, onSubmit, onClose }: ModalTodoFormProps) {
  const {
    register,
    control,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<TodoFormInput>({
    resolver: zodResolver(createTodoSchema),
    defaultValues: {
      title: todo?.title ?? '',
      description: todo?.description ?? '',
      priority: todo?.priority ?? 'medium',
      dueDate: todo?.dueDate ? toDateInputValue(todo.dueDate) : '',
    },
  })

  return (
    <Modal opened onClose={onClose} title={mode === 'edit' ? 'Editar tarefa' : 'Nova tarefa'}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Stack gap="sm">
          <TextInput
            label="Título"
            placeholder="Ex.: Preparar apresentação"
            required
            {...register('title')}
            error={errors.title?.message}
          />
          <Textarea
            label="Descrição"
            placeholder="Detalhes da tarefa (opcional)"
            autosize
            minRows={2}
            maxRows={5}
            {...register('description')}
            error={errors.description?.message}
          />
          <Controller
            control={control}
            name="priority"
            render={({ field }) => <Select label="Prioridade" data={priorityOptions} {...field} />}
          />
          <Controller
            control={control}
            name="dueDate"
            render={({ field }) => (
              <TextInput
                type="date"
                label="Vencimento"
                {...field}
                value={String(field.value ?? '')}
                error={errors.dueDate?.message}
              />
            )}
          />
          <Group justify="flex-end" mt="xs">
            <Button variant="subtle" leftSection={<IconX size={16} />} onClick={onClose}>
              Cancelar
            </Button>
            <Button type="submit" loading={isSubmitting}>
              {mode === 'edit' ? 'Salvar' : 'Criar tarefa'}
            </Button>
          </Group>
        </Stack>
      </form>
    </Modal>
  )
}
