// apps/sveltekit/src/routes/(private)/tarefas/_components/modal-todo-form/modal-todo-form.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { IconX } from '@tabler/icons-svelte'
  import { z } from 'zod'
  import { createTodoSchema } from '@ia-task-manager/schemas/todo'
  import type { CreateTodoFormInput, Todo, TodoPriority } from '@ia-task-manager/schemas/todo'
  import { priorityOptions } from '$lib/constants/todo.constants'
  import { toDateInputValue } from '$lib/utils/date'

  interface Props {
    mode: 'create' | 'edit'
    todo?: Todo
    onsubmit: (values: CreateTodoFormInput) => void
    onclose: () => void
  }

  type TodoFormState = {
    title: string
    description: string
    priority: TodoPriority
    dueDate: string
  }

  type TodoFormErrors = {
    title?: string[]
    description?: string[]
    priority?: string[]
    dueDate?: string[]
  }

  let { mode, todo, onsubmit, onclose }: Props = $props()

  let dialogEl: HTMLDialogElement | undefined = $state()

  let formState = $state<TodoFormState>({
    title: '',
    description: '',
    priority: 'medium',
    dueDate: '',
  })

  let errors = $state<TodoFormErrors>({})

  $effect(() => {
    formState.title = todo?.title ?? ''
    formState.description = todo?.description ?? ''
    formState.priority = todo?.priority ?? 'medium'
    formState.dueDate = todo?.dueDate ? toDateInputValue(todo.dueDate) : ''
  })

  onMount(() => {
    dialogEl?.showModal()
  })

  function handleSubmit(event: SubmitEvent): void {
    event.preventDefault()
    const parsed = createTodoSchema.safeParse({ ...formState })
    if (!parsed.success) {
      errors = z.flattenError(parsed.error).fieldErrors
      return
    }
    errors = {}
    onsubmit({ ...formState })
  }

  function closeDialog(): void {
    dialogEl?.close()
  }

  function onDialogClose(): void {
    onclose()
  }

  function onDialogClick(event: MouseEvent): void {
    if (event.target !== dialogEl) return
    closeDialog()
  }
</script>

<dialog
  bind:this={dialogEl}
  class="dialog animate-dialog card border-line bg-surface border"
  style="--dialog-max-width: 42rem"
  onclose={onDialogClose}
  onclick={onDialogClick}
>
  <div class="flex flex-col gap-4">
    <header class="flex items-center justify-between">
      <h3 class="text-fg text-lg font-semibold">
        {mode === 'edit' ? 'Editar tarefa' : 'Nova tarefa'}
      </h3>
      <button
        type="button"
        class="btn-icon btn-icon-xs preset-tonal"
        aria-label="Fechar"
        onclick={closeDialog}
      >
        <IconX class="size-4" />
      </button>
    </header>

    <form class="flex flex-col gap-4" novalidate onsubmit={handleSubmit}>
      <div class="flex flex-col gap-1">
        <label class="label-text" for="todo-title">Título</label>
        <input
          id="todo-title"
          name="title"
          type="text"
          class="input"
          placeholder="Ex.: Preparar apresentação"
          bind:value={formState.title}
          required
        />
        {#if errors.title}
          <span class="text-error text-xs">{errors.title[0]}</span>
        {/if}
      </div>

      <div class="flex flex-col gap-1">
        <label class="label-text" for="todo-description">Descrição</label>
        <textarea
          id="todo-description"
          name="description"
          class="textarea"
          rows="2"
          placeholder="Detalhes da tarefa (opcional)"
          bind:value={formState.description}></textarea>
        {#if errors.description}
          <span class="text-error text-xs">{errors.description[0]}</span>
        {/if}
      </div>

      <div class="flex flex-col gap-1">
        <label class="label-text" for="todo-priority">Prioridade</label>
        <select id="todo-priority" name="priority" class="select" bind:value={formState.priority}>
          {#each priorityOptions as option (option.value)}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
        {#if errors.priority}
          <span class="text-error text-xs">{errors.priority[0]}</span>
        {/if}
      </div>

      <div class="flex flex-col gap-1">
        <label class="label-text" for="todo-due-date">Vencimento</label>
        <input
          id="todo-due-date"
          name="dueDate"
          type="date"
          class="input"
          bind:value={formState.dueDate}
        />
        {#if errors.dueDate}
          <span class="text-error text-xs">{errors.dueDate[0]}</span>
        {/if}
      </div>

      <div class="flex justify-end gap-2">
        <button type="button" class="btn preset-tonal" onclick={closeDialog}>
          <IconX class="size-4" />
          Cancelar
        </button>
        <button type="submit" class="btn preset-filled-primary-500">
          {mode === 'edit' ? 'Salvar' : 'Criar tarefa'}
        </button>
      </div>
    </form>
  </div>
</dialog>

// apps/nextjs/app/(private)/tarefas/_components/modal-todo-form/modal-todo-form.tsx
'use client'

import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button, Group, Modal, Select, Stack, TextInput, Textarea } from '@mantine/core'
import { IconX } from '@tabler/icons-react'
import type { Todo } from '@ia-task-manager/schemas/todo'
import { priorityOptions } from '@/lib/constants/todo.constants'
import { toDateInputValue } from '@/lib/utils/date'
import { createTodoSchema, type CreateTodoFormInput } from '@ia-task-manager/schemas/todo'

export type TodoFormInput = CreateTodoFormInput

type ModalTodoFormProps = {
  mode: 'create' | 'edit'
  todo?: Todo
  onSubmit: (values: TodoFormInput) => void
  onClose: () => void
}

export function ModalTodoForm({ mode, todo, onSubmit, onClose }: ModalTodoFormProps) {
  const {
    register,
    control,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<TodoFormInput>({
    resolver: zodResolver(createTodoSchema),
    defaultValues: {
      title: todo?.title ?? '',
      description: todo?.description ?? '',
      priority: todo?.priority ?? 'medium',
      dueDate: todo?.dueDate ? toDateInputValue(todo.dueDate) : '',
    },
  })

  return (
    <Modal opened onClose={onClose} title={mode === 'edit' ? 'Editar tarefa' : 'Nova tarefa'}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Stack gap="sm">
          <TextInput
            label="Título"
            placeholder="Ex.: Preparar apresentação"
            required
            {...register('title')}
            error={errors.title?.message}
          />
          <Textarea
            label="Descrição"
            placeholder="Detalhes da tarefa (opcional)"
            autosize
            minRows={2}
            maxRows={5}
            {...register('description')}
            error={errors.description?.message}
          />
          <Controller
            control={control}
            name="priority"
            render={({ field }) => <Select label="Prioridade" data={priorityOptions} {...field} />}
          />
          <Controller
            control={control}
            name="dueDate"
            render={({ field }) => (
              <TextInput
                type="date"
                label="Vencimento"
                {...field}
                value={String(field.value ?? '')}
                error={errors.dueDate?.message}
              />
            )}
          />
          <Group justify="flex-end" mt="xs">
            <Button variant="subtle" leftSection={<IconX size={16} />} onClick={onClose}>
              Cancelar
            </Button>
            <Button type="submit" loading={isSubmitting}>
              {mode === 'edit' ? 'Salvar' : 'Criar tarefa'}
            </Button>
          </Group>
        </Stack>
      </form>
    </Modal>
  )
}
