// apps/nextjs/app/(private)/settings/_components/section-security/section-security.tsx
'use client'

import { Button, Card, PasswordInput, Stack, Title } from '@mantine/core'
import { useForm, schemaResolver } from '@mantine/form'
import { changePasswordSchema, type ChangePasswordInput } from '@ia-task-manager/schemas/auth'
import { notifyError, notifySuccess } from '@/lib/utils/notifications'
import { useChangePasswordMutation } from '@/services/auth'

export function SectionSecurity() {
  const changePassword = useChangePasswordMutation()
  const form = useForm<ChangePasswordInput>({
    initialValues: { currentPassword: '', newPassword: '' },
    validate: schemaResolver(changePasswordSchema),
  })

  function handleSubmit(values: ChangePasswordInput) {
    changePassword.mutate(
      { currentPassword: values.currentPassword, newPassword: values.newPassword },
      {
        onError: notifyError('Não foi possível alterar a senha'),
        onSuccess: () => {
          notifySuccess('Senha alterada', 'Sua senha foi atualizada com sucesso.')
          form.reset()
        },
      },
    )
  }

  return (
    <Card withBorder shadow="sm" padding="lg" className="max-w-md">
      <Title order={4} mb="sm">
        Alterar senha
      </Title>
      <form onSubmit={form.onSubmit(handleSubmit)}>
        <Stack gap="md">
          <PasswordInput
            label="Senha atual"
            placeholder="Sua senha atual"
            {...form.getInputProps('currentPassword')}
          />
          <PasswordInput
            label="Nova senha"
            placeholder="Mínimo de 8 caracteres"
            {...form.getInputProps('newPassword')}
          />
          <Button type="submit" loading={changePassword.isPending} className="self-start">
            Alterar senha
          </Button>
        </Stack>
      </form>
    </Card>
  )
}

// apps/nuxt/app/pages/settings/_components/section-security/section-security.vue
<script setup lang="ts">
import { reactive } from 'vue'
import { changePasswordSchema } from '@ia-task-manager/schemas/auth'
import type { ChangePasswordInput } from '@ia-task-manager/schemas/auth'
import { useNotifications } from '~/lib/utils/notifications'
import { useChangePasswordMutation } from '~/services/auth/auth.mutation'

const { notifyError, notifySuccess } = useNotifications()
const changePasswordMutation = useChangePasswordMutation()

const state = reactive<ChangePasswordInput>({ currentPassword: '', newPassword: '' })

function onSubmit() {
  changePasswordMutation.mutate(
    { currentPassword: state.currentPassword, newPassword: state.newPassword },
    {
      onError: notifyError('Não foi possível alterar a senha'),
      onSuccess: () => {
        notifySuccess('Senha alterada', 'Sua senha foi atualizada com sucesso.')
        state.currentPassword = ''
        state.newPassword = ''
      },
    },
  )
}
</script>

<template>
  <UCard class="max-w-md">
    <div class="flex flex-col gap-4">
      <h2 class="text-highlighted font-semibold">Alterar senha</h2>

      <UForm :schema="changePasswordSchema" :state="state" :transform="false" @submit="onSubmit">
        <div class="flex flex-col gap-4">
          <UFormField label="Senha atual" name="currentPassword" required>
            <UInput
              v-model="state.currentPassword"
              class="w-full"
              type="password"
              placeholder="Sua senha atual"
            />
          </UFormField>

          <UFormField label="Nova senha" name="newPassword" required>
            <UInput
              v-model="state.newPassword"
              class="w-full"
              type="password"
              placeholder="Mínimo de 8 caracteres"
            />
          </UFormField>

          <UButton
            type="submit"
            class="self-start"
            :loading="changePasswordMutation.isPending.value"
          >
            Alterar senha
          </UButton>
        </div>
      </UForm>
    </div>
  </UCard>
</template>
