// apps/nuxt/app/components/TableSortHeader.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Header } from '@tanstack/vue-table'
import type { Todo } from '@ia-task-manager/schemas/todo'

const props = defineProps<{ header: Header<Todo, unknown>; label: string }>()

const sorted = computed(() => props.header.column.getIsSorted())

function toggle(event: MouseEvent) {
  props.header.column.getToggleSortingHandler()?.(event)
}
</script>

<template>
  <button
    type="button"
    class="flex items-center gap-1 text-sm font-medium transition-opacity hover:opacity-70"
    @click="toggle"
  >
    <span>{{ label }}</span>
    <UIcon v-if="sorted === 'asc'" name="i-tabler:arrow-up" class="size-3.5" />
    <UIcon v-else-if="sorted === 'desc'" name="i-tabler:arrow-down" class="size-3.5" />
    <UIcon v-else name="i-tabler:arrows-sort" class="size-3.5 opacity-40" />
  </button>
</template>

// apps/nextjs/app/(private)/tarefas/_components/table-sort-header/table-sort-header.tsx
'use client'

import { Group, Text, UnstyledButton } from '@mantine/core'
import { IconArrowDown, IconArrowUp, IconArrowsSort } from '@tabler/icons-react'
import type { Column } from '@tanstack/react-table'
import type { Todo } from '@ia-task-manager/schemas/todo'
import { todoTableFeatures } from '../table-todo-list/todo-table-features'

type TableSortHeaderProps<TValue> = {
  column: Column<typeof todoTableFeatures, Todo, TValue>
  label: string
}

export function TableSortHeader<TValue>({ column, label }: TableSortHeaderProps<TValue>) {
  const sorted = column.getIsSorted()

  return (
    <UnstyledButton onClick={column.getToggleSortingHandler()}>
      <Group gap={4} wrap="nowrap">
        <Text size="sm" fw={500}>
          {label}
        </Text>
        {sorted === 'asc' && <IconArrowUp size={14} />}
        {sorted === 'desc' && <IconArrowDown size={14} />}
        {!sorted && <IconArrowsSort size={14} opacity={0.4} />}
      </Group>
    </UnstyledButton>
  )
}
