// apps/sveltekit/src/routes/(public)/_components/card-auth/card-auth.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  let { title, children }: { title: string; children: Snippet } = $props()
</script>

<div
  class="animate-in fade-in duration-slow ease-entrance flex min-h-svh items-center justify-center px-4 py-10"
>
  <div class="card border-line bg-surface w-full max-w-md border p-6">
    <h2 class="text-fg mb-6 text-2xl font-semibold">{title}</h2>
    {@render children()}
  </div>
</div>

// apps/nuxt/app/pages/(public)/_components/card-auth/card-auth.vue
<script setup lang="ts">
defineProps<{ title: string }>()
</script>

<template>
  <div
    class="animate-in fade-in duration-slow ease-entrance flex min-h-svh items-center justify-center px-4 py-10"
  >
    <UCard class="w-full max-w-md">
      <h2 class="text-highlighted mb-6 text-2xl font-semibold">
        {{ title }}
      </h2>
      <slot />
    </UCard>
  </div>
</template>
