// apps/nextjs/app/(private)/tarefas/_components/skeleton-todo-manager/skeleton-todo-manager.tsx
import { Skeleton } from '@mantine/core'
import { SkeletonStack } from '@/components/skeleton-stack/skeleton-stack'

export function SkeletonTodoManager() {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <div className="flex flex-col gap-1">
          <Skeleton height={24} width={160} />
          <Skeleton height={12} width={200} />
        </div>
        <div className="flex gap-2">
          <Skeleton height={36} width={150} />
          <Skeleton height={36} width={130} />
        </div>
      </div>
      <SkeletonStack lines={8} rowHeight={36} />
    </div>
  )
}

// apps/sveltekit/src/routes/(private)/tarefas/_components/skeleton-todo-manager/skeleton-todo-manager.svelte
<script lang="ts">
  import SkeletonStack from '$lib/components/skeleton-stack/skeleton-stack.svelte'
</script>

<div class="flex flex-col gap-4">
  <div class="flex flex-wrap items-center justify-between gap-4">
    <div class="flex flex-col gap-1">
      <div
        class="bg-surface-200-800 animate-pulse rounded"
        style="height: 24px; width: 160px;"
      ></div>
      <div
        class="bg-surface-200-800 animate-pulse rounded"
        style="height: 12px; width: 200px;"
      ></div>
    </div>
    <div class="flex gap-2">
      <div
        class="bg-surface-200-800 animate-pulse rounded"
        style="height: 36px; width: 152px;"
      ></div>
      <div
        class="bg-surface-200-800 animate-pulse rounded"
        style="height: 36px; width: 128px;"
      ></div>
    </div>
  </div>
  <SkeletonStack lines={8} rowHeight={36} />
</div>
