// apps/sveltekit/src/routes/(public)/login/_components/form-login/form-login.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { resolve } from '$app/paths'
  import { z } from 'zod'
  import OAuthButtons from '../../../_components/oauth-buttons/oauth-buttons.svelte'
  import { paths, type TPath } from '$lib/constants/paths'
  import { authClient } from '$lib/services/auth/auth.client'
  import { notifyError, notifySuccess } from '$lib/utils/notifications'

  const loginSchema = z.object({
    email: z.email('E-mail inválido'),
    password: z.string().min(1, 'Informe sua senha'),
  })

  let { callbackURL = paths.DASHBOARD }: { callbackURL?: TPath } = $props()

  let email = $state('')
  let password = $state('')
  let errors = $state<{ email?: string[]; password?: string[] }>({})
  let isSubmitting = $state(false)
  let isSocialSubmitting = $state(false)

  async function handleSubmit(event: SubmitEvent): Promise<void> {
    event.preventDefault()

    const parsed = loginSchema.safeParse({ email, password })
    if (!parsed.success) {
      errors = z.flattenError(parsed.error).fieldErrors
      return
    }
    errors = {}

    isSubmitting = true
    try {
      const response = await authClient.signIn.email({ email, password, callbackURL })
      if (response.error) {
        notifyError('Falha ao entrar')(response.error)
        return
      }
      notifySuccess('Login realizado', 'Bem-vindo(a) de volta!')
      await goto(resolve(callbackURL))
    } catch (error) {
      notifyError('Ops, algo deu errado')(error)
    } finally {
      isSubmitting = false
    }
  }

  async function handleSocial(provider: 'google' | 'github'): Promise<void> {
    isSocialSubmitting = true
    try {
      const response = await authClient.signIn.social({ provider, callbackURL })
      if (response.error) {
        notifyError('Falha na autenticação social')(response.error)
      }
    } catch (error) {
      notifyError('Ops, algo deu errado')(error)
    } finally {
      isSocialSubmitting = false
    }
  }
</script>

<form class="flex flex-col gap-4" novalidate onsubmit={handleSubmit}>
  <div class="flex flex-col gap-1">
    <label class="label-text" for="email">E-mail</label>
    <input
      id="email"
      name="email"
      type="email"
      class="input"
      placeholder="voce@exemplo.com"
      autocomplete="email"
      aria-invalid={errors.email ? true : undefined}
      bind:value={email}
    />
    {#if errors.email}
      <span class="text-error text-xs">{errors.email[0]}</span>
    {/if}
  </div>

  <div class="flex flex-col gap-1">
    <label class="label-text" for="password">Senha</label>
    <input
      id="password"
      name="password"
      type="password"
      class="input"
      placeholder="Sua senha"
      autocomplete="current-password"
      aria-invalid={errors.password ? true : undefined}
      bind:value={password}
    />
    {#if errors.password}
      <span class="text-error text-xs">{errors.password[0]}</span>
    {/if}
  </div>

  <button type="submit" class="btn preset-filled-primary-500 w-full" disabled={isSubmitting}>
    Entrar
  </button>

  <div class="relative flex items-center">
    <hr class="hr" />
    <span class="text-muted bg-surface absolute left-1/2 -translate-x-1/2 px-2 text-xs">
      ou continue com
    </span>
  </div>

  <OAuthButtons loading={isSocialSubmitting} onsocial={handleSocial} />

  <p class="text-muted text-center text-sm">
    Ainda não tem conta?
    <a href={resolve(paths.REGISTER)} class="text-accent font-medium hover:underline">
      Crie uma agora
    </a>
  </p>
</form>

// apps/nuxt/app/pages/(public)/login/_components/form-login/form-login.vue
<script setup lang="ts">
import { navigateTo } from '#imports'
import { reactive, ref } from 'vue'
import { z } from 'zod'
import { paths } from '~/lib/constants/paths'
import { useNotifications } from '~/lib/utils/notifications'
import { authClient } from '~/services/auth/auth.client'
import OAuthButtons from '../../../_components/oauth-buttons/oauth-buttons.vue'

const props = defineProps<{ callbackURL?: string }>()

const { notifyError, notifySuccess } = useNotifications()

const loginSchema = z.object({
  email: z.email('E-mail inválido'),
  password: z.string().min(1, 'Informe sua senha'),
})

type LoginValues = z.infer<typeof loginSchema>

const state = reactive<LoginValues>({ email: '', password: '' })
const isSubmitting = ref(false)
const isSocialSubmitting = ref(false)

const callbackURL = props.callbackURL ?? paths.DASHBOARD

async function onSubmit(): Promise<void> {
  isSubmitting.value = true
  try {
    const response = await authClient.signIn.email({
      email: state.email,
      password: state.password,
      callbackURL,
    })
    if (response.error) {
      notifyError('Falha ao entrar')(response.error)
      return
    }
    notifySuccess('Login realizado', 'Bem-vindo(a) de volta!')
    await navigateTo(callbackURL)
  } catch (error) {
    notifyError('Ops, algo deu errado')(error)
  } finally {
    isSubmitting.value = false
  }
}

async function onSocial(provider: 'google' | 'github'): Promise<void> {
  isSocialSubmitting.value = true
  try {
    const response = await authClient.signIn.social({ provider, callbackURL })
    if (response.error) notifyError('Falha na autenticação social')(response.error)
  } catch (error) {
    notifyError('Ops, algo deu errado')(error)
  } finally {
    isSocialSubmitting.value = false
  }
}
</script>

<template>
  <UForm :schema="loginSchema" :state="state" @submit="onSubmit">
    <div class="flex flex-col gap-4">
      <UFormField label="E-mail" name="email" required>
        <UInput v-model="state.email" class="w-full" placeholder="voce@exemplo.com" />
      </UFormField>

      <UFormField label="Senha" name="password" required>
        <UInput v-model="state.password" class="w-full" type="password" placeholder="Sua senha" />
      </UFormField>

      <UButton type="submit" :loading="isSubmitting" block> Entrar </UButton>

      <USeparator label="ou continue com" />

      <OAuthButtons :loading="isSocialSubmitting" @social="onSocial" />

      <p class="text-dimmed text-center text-sm">
        Ainda não tem conta?
        <NuxtLink :to="paths.REGISTER" class="text-primary font-medium hover:underline">
          Crie uma agora
        </NuxtLink>
      </p>
    </div>
  </UForm>
</template>
