// apps/nuxt/app/pages/tarefas/_components/modal-ai-suggest/modal-ai-suggest.vue
<script setup lang="ts">
import { ref } from 'vue'
import { priorityColors, priorityLabels } from '~/lib/constants/todo.constants'
import { useNotifications } from '~/lib/utils/notifications'
import { useSuggestTodoMutation } from '~/services/todo/todo.mutation'
import type { TodoSuggestion } from '@ia-task-manager/schemas/todo'

const props = defineProps<{ adding: boolean }>()
const emit = defineEmits<{ add: [suggestion: TodoSuggestion] }>()

const open = defineModel<boolean>('open', { required: true })

type DraftState = {
  title: string
  description: string
}

const draft = ref<DraftState>({ title: '', description: '' })
const suggestion = ref<TodoSuggestion | null>(null)

const suggestMutation = useSuggestTodoMutation()
const { notifyError } = useNotifications()

const isSuggesting = suggestMutation.isPending

function onUpdateOpen(value: boolean) {
  if (!value) {
    handleClose()
    return
  }
  open.value = true
}

function handleClose() {
  if (isSuggesting.value) return
  open.value = false
  suggestion.value = null
  draft.value = { title: '', description: '' }
}

function resetSuggestion() {
  suggestion.value = null
  suggestMutation.error.value = null
  suggestMutation.data.value = null
}

function onSuggest() {
  suggestMutation.mutate(draft.value, {
    onSuccess: (data) => {
      suggestion.value = data
    },
    onError: notifyError('Não consegui sugerir'),
  })
}

function onAdd() {
  if (!suggestion.value) return
  emit('add', suggestion.value)
}
</script>

<template>
  <UModal
    :open="open"
    title="Sugerir tarefa com IA"
    :dismissible="!isSuggesting"
    :ui="{ content: 'max-w-2xl' }"
    @update:open="onUpdateOpen"
  >
    <div v-if="!suggestion" class="flex flex-col gap-4">
      <p class="text-dimmed text-sm">
        Descreva o que você precisa — pode ser só um tema, uma frase ou um rascunho. A IA estrutura
        em título, descrição, prioridade e subtasks.
      </p>

      <UFormField label="Tema / título (opcional)">
        <UInput v-model="draft.title" class="w-full" placeholder="Montar plano de estudos" />
      </UFormField>

      <UFormField label="Descrição / contexto (opcional)">
        <UTextarea
          v-model="draft.description"
          class="w-full"
          autoresize
          :rows="2"
          :maxrows="4"
          placeholder="Preciso revisar cálculo e física até sexta-feira…"
        />
      </UFormField>

      <div class="flex justify-end gap-2">
        <UButton variant="subtle" @click="handleClose">Cancelar</UButton>
        <UButton icon="i-tabler:sparkles" :loading="isSuggesting" @click="onSuggest">
          Sugerir
        </UButton>
      </div>
    </div>

    <div v-else class="flex flex-col gap-4">
      <p class="text-dimmed text-sm">Sugestão da IA — revise e adicione:</p>

      <UCard v-if="suggestion.subtasks.length > 0">
        <div class="flex flex-col gap-1">
          <div
            v-for="subtask in suggestion.subtasks"
            :key="subtask"
            class="flex items-center gap-2"
          >
            <UIcon name="i-tabler:sparkles" class="text-primary size-3.5 shrink-0" />
            <p class="text-sm">{{ subtask }}</p>
          </div>
        </div>
      </UCard>

      <UCard class="cursor-pointer" @click="resetSuggestion">
        <div class="flex items-center justify-between gap-3">
          <p class="font-semibold">{{ suggestion.title }}</p>
          <UBadge :color="priorityColors[suggestion.priority]" variant="soft">
            {{ priorityLabels[suggestion.priority] }}
          </UBadge>
        </div>
        <p v-if="suggestion.description" class="text-dimmed mt-1 text-sm">
          {{ suggestion.description }}
        </p>
      </UCard>

      <div class="flex justify-end gap-2">
        <UButton variant="subtle" @click="resetSuggestion">Refazer sugestão</UButton>
        <UButton icon="i-tabler:plus" :loading="props.adding" @click="onAdd">
          Adicionar tarefa
        </UButton>
      </div>
    </div>
  </UModal>
</template>

// app/tarefas/_components/modal-ai-suggest/modal-ai-suggest.tsx
'use client'

import { useState } from 'react'
import { Badge, Button, Card, Group, Modal, Stack, Text, Textarea, TextInput } from '@mantine/core'
import { IconPlus, IconSparkles } from '@tabler/icons-react'
import type { TodoSuggestion } from '@/lib/schemas/todo'
import type { DraftInput } from '@/lib/schemas/todo'
import { priorityColors, priorityLabels } from '@/lib/constants/todo.constants'
import { notifyError } from '@/lib/utils/notifications'
import { useSuggestTodoMutation } from '@/services/todo/todo.mutation'

type ModalAiSuggestProps = {
  opened: boolean
  onClose: () => void
  adding: boolean
  onAdd: (suggestion: TodoSuggestion) => void
}

export function ModalAiSuggest({ opened, onClose, adding, onAdd }: ModalAiSuggestProps) {
  const [draft, setDraft] = useState<DraftInput>({})
  const [suggestion, setSuggestion] = useState<TodoSuggestion | null>(null)

  const suggestMutation = useSuggestTodoMutation()

  const handleClose = () => {
    if (suggestMutation.isPending) return
    onClose()
    setSuggestion(null)
    setDraft({})
  }

  const resetSuggestion = () => {
    setSuggestion(null)
    suggestMutation.reset()
  }

  return (
    <Modal opened={opened} onClose={handleClose} title="Sugerir tarefa com IA" size="lg">
      {!suggestion ? (
        <Stack gap="sm">
          <Text size="sm" c="dimmed">
            Descreva o que você precisa — pode ser só um tema, uma frase ou um rascunho. A IA
            estrutura em título, descrição, prioridade e subtasks.
          </Text>
          <TextInput
            label="Tema / título (opcional)"
            placeholder="Montar plano de estudos"
            value={draft.title ?? ''}
            onChange={(event) => setDraft({ ...draft, title: event.currentTarget.value })}
          />
          <Textarea
            label="Descrição / contexto (opcional)"
            placeholder="Preciso revisar cálculo e física até sexta-feira…"
            autosize
            minRows={2}
            maxRows={4}
            value={draft.description ?? ''}
            onChange={(event) => setDraft({ ...draft, description: event.currentTarget.value })}
          />
          <Group justify="flex-end">
            <Button variant="subtle" onClick={handleClose}>
              Cancelar
            </Button>
            <Button
              leftSection={<IconSparkles size={16} />}
              loading={suggestMutation.isPending}
              onClick={() =>
                suggestMutation.mutate(draft, {
                  onSuccess: setSuggestion,
                  onError: notifyError('Não consegui sugerir'),
                })
              }
            >
              Sugerir
            </Button>
          </Group>
        </Stack>
      ) : (
        <Stack gap="sm">
          <Text size="sm" c="dimmed">
            Sugestão da IA — revise e adicione:
          </Text>
          {suggestion.subtasks.length > 0 && (
            <Card withBorder shadow="sm" padding="lg" bg="var(--mantine-color-gray-0)">
              <Stack gap={4}>
                {suggestion.subtasks.map((subtask) => (
                  <Group key={subtask} gap="xs">
                    <IconSparkles size={14} />
                    <Text size="sm">{subtask}</Text>
                  </Group>
                ))}
              </Stack>
            </Card>
          )}
          <Card
            withBorder
            shadow="sm"
            padding="lg"
            onClick={resetSuggestion}
            style={{ cursor: 'pointer' }}
          >
            <Group justify="space-between">
              <Text fw={600}>{suggestion.title}</Text>
              <Badge color={priorityColors[suggestion.priority]} variant="light">
                {priorityLabels[suggestion.priority]}
              </Badge>
            </Group>
            {suggestion.description && (
              <Text size="sm" c="dimmed" mt={4}>
                {suggestion.description}
              </Text>
            )}
          </Card>
          <Group justify="flex-end">
            <Button variant="subtle" onClick={resetSuggestion}>
              Refazer sugestão
            </Button>
            <Button
              leftSection={<IconPlus size={16} />}
              loading={adding}
              onClick={() => onAdd(suggestion)}
            >
              Adicionar tarefa
            </Button>
          </Group>
        </Stack>
      )}
    </Modal>
  )
}
