// apps/sveltekit/src/routes/(public)/register/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import CardAuth from '../_components/card-auth/card-auth.svelte'
  import FormRegister from './_components/form-register/form-register.svelte'
  import { paths, type TPath } from '$lib/constants/paths'

  const callbackURL = (page.url.searchParams.get('next') || paths.DASHBOARD) as TPath
</script>

<svelte:head>
  <title>Criar conta | ia-task-manager</title>
</svelte:head>

<CardAuth title="ia-task-manager">
  <FormRegister {callbackURL} />
</CardAuth>

// apps/nextjs/app/(public)/register/page.tsx
import { Suspense } from 'react'
import type { Metadata } from 'next'
import { CardAuth } from '../_components/card-auth/card-auth'
import { FormRegister } from './_components/form-register/form-register'

export const metadata: Metadata = {
  title: 'Criar conta | ia-task-manager',
}

type RegisterPageProps = {
  searchParams: Promise<{ next?: string }>
}

export default async function RegisterPage({ searchParams }: RegisterPageProps) {
  const { next } = await searchParams

  return (
    <CardAuth title="ia-task-manager">
      <Suspense>
        <FormRegister callbackURL={next} />
      </Suspense>
    </CardAuth>
  )
}
