// apps/nextjs/app/(private)/tarefas/_components/content-todo-manager/content-todo-manager.tsx
'use client'

import { useCallback, useState } from 'react'
import { Button, Card, Group, Text, Title } from '@mantine/core'
import { IconPlus, IconSparkles } from '@tabler/icons-react'
import type { Todo } from '@ia-task-manager/schemas/todo'
import { notifyError, notifySuccess } from '@/lib/utils/notifications'
import { useCreateTodoMutation, useUpdateTodoMutation } from '@/services/todo/todo.mutation'
import { useTodosQuery } from '@/services/todo/todo.query'
import { FilterTodoList } from '../filter-todo-list/filter-todo-list'
import { ModalTodoForm, type TodoFormInput } from '../modal-todo-form/modal-todo-form'
import { ModalAiSuggest } from '../modal-ai-suggest/modal-ai-suggest'
import { TableTodoList } from '../table-todo-list/table-todo-list'

type FormModalState = {
  mode: 'create' | 'edit'
  todo?: Todo
}

export function ContentTodoManager() {
  const [formModal, setFormModal] = useState<FormModalState | null>(null)
  const [aiOpened, setAiOpened] = useState<boolean>(false)

  const { data: todos } = useTodosQuery()

  const createMutation = useCreateTodoMutation()
  const updateMutation = useUpdateTodoMutation()

  const handleSubmit = (mode: 'create' | 'edit', todo?: Todo) => (values: TodoFormInput) => {
    if (mode !== 'edit' || !todo) {
      createMutation.mutate(values, {
        onSuccess: () => {
          notifySuccess('Tarefa criada', 'A tarefa foi criada com sucesso.')
          setFormModal(null)
        },
        onError: notifyError('Erro ao criar'),
      })
      return
    }
    updateMutation.mutate(
      { id: todo.id, input: values },
      {
        onSuccess: () => {
          notifySuccess('Tarefa atualizada', 'As alterações foram salvas.')
          setFormModal(null)
        },
        onError: notifyError('Erro ao atualizar'),
      },
    )
  }

  const pendingCount = todos.filter((t) => !t.completed).length

  const handleEdit = useCallback((todo: Todo) => {
    setFormModal({ mode: 'edit', todo })
  }, [])

  return (
    <div className="flex flex-col gap-4">
      <Group justify="space-between">
        <div>
          <Title order={3}>Tarefas</Title>
          <Text size="sm" c="dimmed">
            {todos.length} no total · {pendingCount} pendentes
          </Text>
        </div>
        <Group>
          <Button
            variant="light"
            leftSection={<IconSparkles size={18} />}
            onClick={() => setAiOpened(true)}
          >
            Sugerir com IA
          </Button>
          <Button
            leftSection={<IconPlus size={18} />}
            onClick={() => setFormModal({ mode: 'create' })}
          >
            Nova tarefa
          </Button>
        </Group>
      </Group>

      <FilterTodoList />

      <Card withBorder shadow="sm" padding="lg" pos="relative">
        <TableTodoList todos={todos} onEdit={handleEdit} />
      </Card>

      {formModal && (
        <ModalTodoForm
          mode={formModal.mode}
          todo={formModal.todo}
          onSubmit={handleSubmit(formModal.mode, formModal.todo)}
          onClose={() => setFormModal(null)}
        />
      )}

      <ModalAiSuggest
        opened={aiOpened}
        onClose={() => setAiOpened(false)}
        adding={createMutation.isPending}
        onAdd={(suggestion) => {
          createMutation.mutate(suggestion, {
            onSuccess: () => {
              notifySuccess('Tarefa criada', 'A tarefa foi criada com sucesso.')
              setAiOpened(false)
            },
            onError: notifyError('Erro ao criar'),
          })
        }}
      />
    </div>
  )
}

// apps/sveltekit/src/routes/(private)/tarefas/_components/content-todo-manager/content-todo-manager.svelte
<script lang="ts">
  import { IconPlus, IconSparkles } from '@tabler/icons-svelte'
  import type { CreateTodoFormInput, Todo, TodoSuggestion } from '@ia-task-manager/schemas/todo'
  import FilterTodoList from '../filter-todo-list/filter-todo-list.svelte'
  import ModalAiSuggest from '../modal-ai-suggest/modal-ai-suggest.svelte'
  import ModalTodoForm from '../modal-todo-form/modal-todo-form.svelte'
  import TableTodoList from '../table-todo-list/table-todo-list.svelte'
  import { useCreateTodoMutation, useUpdateTodoMutation } from '$lib/services/todo/todo.mutation'
  import { notifyError, notifySuccess } from '$lib/utils/notifications'

  interface Props {
    todos: Todo[]
  }

  type FormModalState = {
    mode: 'create' | 'edit'
    todo?: Todo
  }

  let { todos }: Props = $props()

  const createMutation = useCreateTodoMutation()
  const updateMutation = useUpdateTodoMutation()

  let formModal = $state<FormModalState | null>(null)
  let aiOpened = $state(false)

  const pendingCount = $derived(todos.filter((todo) => !todo.completed).length)
  const isCreating = $derived(createMutation.isPending)

  function openCreate(): void {
    formModal = { mode: 'create' }
  }

  function openAi(): void {
    aiOpened = true
  }

  function handleEdit(todo: Todo): void {
    formModal = { mode: 'edit', todo }
  }

  function handleSubmit(values: CreateTodoFormInput): void {
    const modal = formModal
    if (!modal || modal.mode !== 'edit' || !modal.todo) {
      createMutation.mutate(values, {
        onSuccess: () => {
          notifySuccess('Tarefa criada', 'A tarefa foi criada com sucesso.')
          formModal = null
        },
        onError: notifyError('Erro ao criar'),
      })
      return
    }

    updateMutation.mutate(
      { id: modal.todo.id, input: values },
      {
        onSuccess: () => {
          notifySuccess('Tarefa atualizada', 'As alterações foram salvas.')
          formModal = null
        },
        onError: notifyError('Erro ao atualizar'),
      },
    )
  }

  function onAdd(suggestion: TodoSuggestion): void {
    createMutation.mutate(suggestion, {
      onSuccess: () => {
        notifySuccess('Tarefa criada', 'A tarefa foi criada com sucesso.')
        aiOpened = false
      },
      onError: notifyError('Erro ao criar'),
    })
  }
</script>

<div class="flex flex-col gap-4">
  <div class="flex flex-wrap items-start justify-between gap-4">
    <div>
      <h2 class="text-fg text-xl font-bold">Tarefas</h2>
      <p class="text-muted text-sm">{todos.length} no total · {pendingCount} pendentes</p>
    </div>
    <div class="flex gap-2">
      <button type="button" class="btn preset-tonal" onclick={openAi}>
        <IconSparkles class="size-[18px]" />
        Sugerir com IA
      </button>
      <button type="button" class="btn preset-filled-primary-500" onclick={openCreate}>
        <IconPlus class="size-[18px]" />
        Nova tarefa
      </button>
    </div>
  </div>

  <FilterTodoList />

  <div class="card border-line bg-surface border p-4">
    <TableTodoList {todos} onedit={handleEdit} />
  </div>

  {#if formModal}
    <ModalTodoForm
      mode={formModal.mode}
      todo={formModal.todo}
      onsubmit={handleSubmit}
      onclose={() => (formModal = null)}
    />
  {/if}

  <ModalAiSuggest
    open={aiOpened}
    adding={isCreating}
    onadd={onAdd}
    onclose={() => (aiOpened = false)}
  />
</div>
