// apps/sveltekit/src/routes/(private)/dashboard/+page.svelte
<script lang="ts">
  import { resolve } from '$app/paths'
  import { IconClipboardList, IconSearch, IconSettings, IconSparkles } from '@tabler/icons-svelte'
  import { paths } from '$lib/constants/paths'
  import type { PageProps } from './$types'

  let { data }: PageProps = $props()

  const firstName = $derived(data.user.name.trim().split(' ')[0] ?? '')

  const shortcuts = [
    {
      to: paths.TAREFAS,
      icon: IconClipboardList,
      title: 'Tarefas',
      description: 'Gerencie suas tarefas com tabela, filtros e sugestão de IA.',
      cta: 'Abrir tarefas',
    },
    {
      to: paths.RESUMO,
      icon: IconSparkles,
      title: 'Resumo do dia',
      description: 'A IA organiza suas pendências em um plano de execução.',
      cta: 'Gerar resumo',
    },
    {
      to: paths.BUSCA,
      icon: IconSearch,
      title: 'Busca por IA',
      description: 'Pergunte em linguagem natural e a IA filtra seus dados.',
      cta: 'Fazer uma busca',
    },
  ]
</script>

<svelte:head>
  <title>Dashboard | ia-task-manager</title>
</svelte:head>

<div class="mx-auto flex max-w-5xl flex-col gap-8 px-4 py-6">
  <div class="flex flex-col gap-2">
    <h1 class="text-highlighted text-3xl/tight font-bold">
      {firstName ? `Olá, ${firstName} 👋` : 'Dashboard'}
    </h1>
    <p class="text-dimmed text-lg">Sua central de produtividade com IA. Escolha onde começar.</p>
  </div>

  <div class="grid gap-4 sm:grid-cols-3">
    {#each shortcuts as { to, icon: Icon, title, description, cta } (to)}
      <a
        href={resolve(to)}
        class="card border-line bg-surface border transition-shadow hover:shadow-md focus-visible:ring-ring focus-visible:ring-2 focus-visible:outline-none"
      >
        <div class="flex h-full flex-col gap-4 p-6">
          <span
            class="bg-accent-soft text-accent flex size-10 items-center justify-center rounded-lg"
          >
            <Icon class="size-5" />
          </span>
          <div class="flex flex-col gap-1.5">
            <p class="text-highlighted font-semibold">{title}</p>
            <p class="text-dimmed text-sm">{description}</p>
          </div>
          <span
            class="text-accent hover:bg-accent-soft mt-auto block w-full rounded-md px-3 py-1.5 text-center text-sm font-medium"
          >
            {cta}
          </span>
        </div>
      </a>
    {/each}
  </div>

  <div>
    <a href={resolve(paths.SETTINGS)} class="btn preset-tonal">
      <IconSettings />
      Gerenciar minha conta
    </a>
  </div>
</div>

// app/(private)/dashboard/page.tsx
import Link from 'next/link'
import { Button, Card, SimpleGrid, Text, ThemeIcon, Title } from '@mantine/core'
import { IconClipboardList, IconSearch, IconSettings, IconSparkles } from '@tabler/icons-react'
import { verifySession } from '@/lib/auth/session'
import { paths } from '@/lib/constants/router-paths'

const shortcuts = [
  {
    href: paths.TAREFAS,
    icon: IconClipboardList,
    title: 'Tarefas',
    description: 'Gerencie suas tarefas com tabela, filtros e sugestão de IA.',
    cta: 'Abrir tarefas',
  },
  {
    href: paths.RESUMO,
    icon: IconSparkles,
    title: 'Resumo do dia',
    description: 'A IA organiza suas pendências em um plano de execução.',
    cta: 'Gerar resumo',
  },
  {
    href: paths.BUSCA,
    icon: IconSearch,
    title: 'Busca por IA',
    description: 'Pergunte em linguagem natural e a IA filtra seus dados.',
    cta: 'Fazer uma busca',
  },
]

export default async function DashboardPage() {
  const user = await verifySession()

  return (
    <div className="mx-auto flex max-w-5xl flex-col gap-8 py-6">
      <div className="flex flex-col gap-2">
        <Title order={1}>Olá, {user.name.split(' ')[0]} 👋</Title>
        <Text size="lg" c="dimmed">
          Sua central de produtividade com IA. Escolha onde começar.
        </Text>
      </div>

      <SimpleGrid cols={{ base: 1, sm: 3 }} spacing="md">
        {shortcuts.map((shortcut) => {
          const Icon = shortcut.icon
          return (
            <Link
              key={shortcut.href}
              href={shortcut.href}
              className="transition-shadow hover:shadow-md"
            >
              <Card withBorder shadow="sm" padding="lg" h="100%">
                <ThemeIcon variant="light" size="xl" radius="md" mb="sm">
                  <Icon size={22} />
                </ThemeIcon>
                <Title order={4} mb={6}>
                  {shortcut.title}
                </Title>
                <Text size="sm" c="dimmed" mb="lg">
                  {shortcut.description}
                </Text>
                <Button variant="subtle" size="xs" fullWidth>
                  {shortcut.cta}
                </Button>
              </Card>
            </Link>
          )
        })}
      </SimpleGrid>

      <div>
        <Link href={paths.SETTINGS}>
          <Button variant="light" leftSection={<IconSettings size={18} />}>
            Gerenciar minha conta
          </Button>
        </Link>
      </div>
    </div>
  )
}
