// apps/sveltekit/src/lib/components/ProviderAccountItem.svelte
<script lang="ts">
  import { IconExternalLink, IconLinkOff, type Icon as IconType } from '@tabler/icons-svelte'

  interface Props {
    label: string
    icon: IconType
    linked: boolean
    busy: boolean
    onlink: () => void
    onunlink: () => void
  }

  let { label, icon: Icon, linked, busy, onlink, onunlink }: Props = $props()
</script>

<div class="flex flex-wrap items-center justify-between gap-2">
  <div class="flex min-w-0 items-center gap-3">
    <Icon class="size-[18px] shrink-0" />
    <span>{label}</span>
    {#if linked}
      <span class="badge preset-tonal-success">Vinculada</span>
    {:else}
      <span class="badge preset-tonal">Não vinculada</span>
    {/if}
  </div>

  {#if linked}
    <button
      type="button"
      class="btn btn-xs preset-tonal-error"
      disabled={busy}
      onclick={() => onunlink()}
    >
      <IconLinkOff class="size-4" />
      Desvincular
    </button>
  {:else}
    <button type="button" class="btn btn-xs preset-tonal" disabled={busy} onclick={() => onlink()}>
      <IconExternalLink class="size-4" />
      Vincular
    </button>
  {/if}
</div>

// apps/nuxt/app/pages/settings/_components/provider-account-item/provider-account-item.vue
<script setup lang="ts">
const props = defineProps<{
  label: string
  icon: string
  linked: boolean
  busy: boolean
}>()

const emit = defineEmits<{ link: []; unlink: [] }>()
</script>

<template>
  <div class="flex flex-wrap items-center justify-between gap-2">
    <div class="flex min-w-0 items-center gap-3">
      <UIcon :name="props.icon" class="size-[18px] shrink-0" />
      <span>{{ props.label }}</span>
      <UBadge v-if="props.linked" color="success" variant="soft" size="sm">Vinculada</UBadge>
      <UBadge v-else color="neutral" variant="outline" size="sm">Não vinculada</UBadge>
    </div>

    <UButton
      v-if="props.linked"
      icon="i-tabler:link-off"
      size="xs"
      color="error"
      variant="soft"
      :loading="props.busy"
      @click="emit('unlink')"
    >
      Desvincular
    </UButton>
    <UButton v-else icon="i-tabler:external-link" size="xs" variant="soft" @click="emit('link')">
      Vincular
    </UButton>
  </div>
</template>
