// apps/nextjs/components/color-mode-toggle.tsx
'use client'

import { Button, useMantineColorScheme, type ButtonProps } from '@mantine/core'

/**
 * Alterna light/dark.
 *
 * `modes.css` reage a `data-mantine-color-scheme`, que e o atributo que o proprio
 * Mantine escreve. O provider e a UI nao reescrevem `data-mode`, entao nao ha
 * duas fontes de verdade para divergirem.
 *
 * O icone e escolhido por CSS (`dark:hidden` / `hidden dark:inline`) em vez de
 * JS: `useComputedColorScheme` devolve `undefined` no servidor, e decidir o
 * icone no cliente produziria hydration mismatch. Como o `dark` do Tailwind
 * le o mesmo atributo do Mantine, CSS e JS nunca discordam.
 */
export function ColorModeToggle(props: ButtonProps) {
  const { toggleColorScheme } = useMantineColorScheme()

  return (
    <Button
      {...props}
      variant="default"
      aria-label="Alternar tema"
      title="Alternar tema"
      onClick={() => toggleColorScheme()}
    >
      <span aria-hidden="true" className="dark:hidden">
        ☀
      </span>
      <span aria-hidden="true" className="hidden dark:inline">
        ☾
      </span>
    </Button>
  )
}

// apps/nuxt/app/components/ColorModeToggle.vue
<script setup lang="ts">
/**
 * Alterna light/dark.
 *
 * `useColorMode` vem do `@nuxtjs/color-mode` (instalado como dependencia do
 * `@nuxt/ui`) e escreve a classe `dark` no <html>, que e um dos seletores que o
 * `modes.css` escuta. O provider e a UI nao reescrevem `data-mode`, entao nao
 * ha duas fontes de verdade para divergirem.
 *
 * O icone e escolhido por CSS (`dark:hidden` / `hidden dark:inline`) em vez de
 * JS: `colorMode.unknown` e `true` no servidor, e decidir o icone no cliente
 * produziria hydration mismatch. Como o `dark` do Tailwind le a mesma classe
 * que o `color-mode` escreve, CSS e JS nunca discordam.
 */
const colorMode = useColorMode()
</script>

<template>
  <UButton
    color="neutral"
    variant="ghost"
    aria-label="Alternar tema"
    title="Alternar tema"
    @click="colorMode.toggle()"
  >
    <span aria-hidden="true" class="dark:hidden">☀</span>
    <span aria-hidden="true" class="hidden dark:inline">☾</span>
  </UButton>
</template>
