// apps/nextjs/app/(private)/settings/_components/settings-panel.tsx
'use client'

import { Tabs, Title } from '@mantine/core'
import { IconFingerprint, IconLink, IconUserCircle, IconWorld } from '@tabler/icons-react'
import { SectionProfile } from './section-profile/section-profile'
import { SectionSecurity } from './section-security/section-security'
import { SectionAccounts } from './section-accounts/section-accounts'
import { SectionSessions } from './section-sessions/section-sessions'

export function SettingsPanel() {
  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-4 py-6">
      <Title order={1}>Configurações</Title>
      <Tabs defaultValue="profile" orientation="vertical" keepMounted>
        <Tabs.List>
          <Tabs.Tab value="profile" leftSection={<IconUserCircle size={16} />}>
            Perfil
          </Tabs.Tab>
          <Tabs.Tab value="security" leftSection={<IconFingerprint size={16} />}>
            Segurança
          </Tabs.Tab>
          <Tabs.Tab value="accounts" leftSection={<IconLink size={16} />}>
            Contas vinculadas
          </Tabs.Tab>
          <Tabs.Tab value="sessions" leftSection={<IconWorld size={16} />}>
            Sessões ativas
          </Tabs.Tab>
        </Tabs.List>

        <div className="min-w-0 flex-1">
          <Tabs.Panel value="profile" p="md">
            <SectionProfile />
          </Tabs.Panel>
          <Tabs.Panel value="security" p="md">
            <SectionSecurity />
          </Tabs.Panel>
          <Tabs.Panel value="accounts" p="md">
            <SectionAccounts />
          </Tabs.Panel>
          <Tabs.Panel value="sessions" p="md">
            <SectionSessions />
          </Tabs.Panel>
        </div>
      </Tabs>
    </div>
  )
}

// apps/nuxt/app/pages/settings/_components/settings-panel/settings-panel.vue
<script setup lang="ts">
import type { TabsItem } from '@nuxt/ui'
import SectionAccounts from '../section-accounts/section-accounts.vue'
import SectionProfile from '../section-profile/section-profile.vue'
import SectionSecurity from '../section-security/section-security.vue'
import SectionSessions from '../section-sessions/section-sessions.vue'

const items = [
  { value: 'profile', label: 'Perfil', icon: 'i-tabler:user-circle', slot: 'profile' },
  { value: 'security', label: 'Segurança', icon: 'i-tabler:fingerprint', slot: 'security' },
  { value: 'accounts', label: 'Contas vinculadas', icon: 'i-tabler:link', slot: 'accounts' },
  { value: 'sessions', label: 'Sessões ativas', icon: 'i-tabler:world', slot: 'sessions' },
] satisfies TabsItem[]
</script>

<template>
  <div class="flex flex-col gap-4">
    <h1 class="text-highlighted text-3xl/tight font-bold">Configurações</h1>

    <UTabs :items="items" orientation="vertical" default-value="profile" :unmount-on-hide="false">
      <template #profile>
        <SectionProfile />
      </template>
      <template #security>
        <SectionSecurity />
      </template>
      <template #accounts>
        <SectionAccounts />
      </template>
      <template #sessions>
        <SectionSessions />
      </template>
    </UTabs>
  </div>
</template>
