// apps/sveltekit/src/routes/(private)/resumo/_components/card-day-summary-content/card-day-summary-content.svelte
<script lang="ts">
  import { IconCircleCheck } from '@tabler/icons-svelte'
  import SkeletonStack from '$lib/components/skeleton-stack/skeleton-stack.svelte'
  import type { DaySummary } from '@ia-task-manager/schemas/insights'

  interface Props {
    summary?: DaySummary | null
    isPending: boolean
  }

  let { summary, isPending }: Props = $props()
</script>

{#if isPending}
  <div class="card border-line bg-surface border p-6">
    <SkeletonStack rowHeight={14} />
  </div>
{:else if summary}
  <div class="card border-line bg-surface flex flex-col gap-4 border p-6">
    <p>{summary.summary}</p>

    <div>
      <div class="mb-1.5 flex items-center gap-2">
        <span
          class="bg-accent-soft text-accent flex size-5 items-center justify-center rounded-full"
        >
          <IconCircleCheck class="size-4" />
        </span>
        <p class="text-sm font-semibold">Foco principal</p>
      </div>
      <p class="text-muted text-sm">{summary.focus}</p>
    </div>

    {#if summary.suggestedOrder.length > 0}
      <div>
        <p class="mb-1.5 text-sm font-semibold">Ordem sugerida</p>
        <ul class="flex list-disc flex-col gap-2 pl-5">
          {#each summary.suggestedOrder as item (item)}
            <li class="text-sm">{item}</li>
          {/each}
        </ul>
      </div>
    {/if}
  </div>
{/if}

// apps/nextjs/app/(private)/resumo/_components/card-day-summary-content/card-day-summary-content.tsx
import { Card, Group, List, Stack, Text, ThemeIcon } from '@mantine/core'
import { IconCircleCheck } from '@tabler/icons-react'
import type { DaySummary } from '@ia-task-manager/schemas/insights'
import { SkeletonStack } from '@/components/skeleton-stack/skeleton-stack'

type CardDaySummaryContentProps = {
  summary: DaySummary | undefined
  isPending: boolean
}

export function CardDaySummaryContent({ summary, isPending }: CardDaySummaryContentProps) {
  if (isPending) {
    return (
      <Card withBorder shadow="sm" padding="lg">
        <SkeletonStack rowHeight={14} />
      </Card>
    )
  }

  if (!summary) return null

  return (
    <Card withBorder shadow="sm" padding="lg">
      <Stack gap="md">
        <Text>{summary.summary}</Text>

        <div>
          <Group gap="xs" mb={6}>
            <ThemeIcon variant="light" size="sm" radius="xl">
              <IconCircleCheck size={16} />
            </ThemeIcon>
            <Text fw={600} size="sm">
              Foco principal
            </Text>
          </Group>
          <Text size="sm" c="dimmed">
            {summary.focus}
          </Text>
        </div>

        {summary.suggestedOrder.length > 0 && (
          <div>
            <Text fw={600} size="sm" mb={6}>
              Ordem sugerida
            </Text>
            <List spacing="xs" withPadding>
              {summary.suggestedOrder.map((item) => (
                <List.Item key={item}>{item}</List.Item>
              ))}
            </List>
          </div>
        )}
      </Stack>
    </Card>
  )
}
